name = "Checkerboard"
uuid = "b297549e-c8cb-44e5-9c33-b7e2667db6fc"
authors = ["Benjamin Cohen-Stead <benwcs@gmail.com>"]
version = "1.2.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
